import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Inter } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "@/context/authSessionProvider";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/context/themeProvider";
import NProgressProvider from "@/context/NProgressProvider";
import CredentialContextProvider from "@/context/credentialProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // You can adjust weights
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // You can adjust weights
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Todo",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${inter.variable} antialiased `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthSessionProvider>
            <NProgressProvider>
              <CredentialContextProvider>

                <div className="min-h-screen">
                  {children}

                </div>
              </CredentialContextProvider>
            </NProgressProvider>
            <Toaster richColors position="top-center" />
          </AuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
